<a href="https://colab.research.google.com/github/saugata-malakar/Summer-Analytics-2021-IIT-Guwahati/blob/main/tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

2.5.1+cu124


In [3]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU is available!
Using GPU: Tesla T4


## Creating a Tensor

In [4]:
# using empty
a = torch.empty(2,3)

In [5]:
# check type
type(a)

torch.Tensor

In [6]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
# using rand
torch.rand(2,3)

tensor([[0.4014, 0.6760, 0.7088],
        [0.5487, 0.7469, 0.0519]])

In [9]:
# use of seed
torch.rand(2,3)

tensor([[0.7320, 0.8042, 0.0715],
        [0.9117, 0.0559, 0.4188]])

In [10]:
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [12]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [13]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [14]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [15]:
x.shape

torch.Size([2, 3])

In [16]:
torch.empty_like(x)

tensor([[                  0, 7310593858020254331, 3616445622929465956],
        [6068934943532133685, 3617580409475969585, 6499591683770496558]])

In [17]:
 torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [18]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [19]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## Tensor Data Types

In [20]:
# find data type
x.dtype

torch.int64

In [21]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [22]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [23]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


## Mathematical operations

### 1. Scalar operation

In [25]:
x = torch.rand(2,2)

x

tensor([[0.9969, 0.7565],
        [0.2239, 0.3023]])

In [26]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.9938, 0.5723],
        [0.0501, 0.0914]])

### 2. Element wise operation

In [27]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.1784, 0.8238, 0.5557],
        [0.9770, 0.4440, 0.9478]])
tensor([[0.7445, 0.4892, 0.2426],
        [0.7003, 0.5277, 0.2472]])


In [28]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.1784, 0.3346, 0.0706],
        [0.2767, 0.4440, 0.2063]])

In [29]:
c = torch.tensor([1, -2, 3, -4])

In [30]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [31]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [32]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [33]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [34]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [35]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [36]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction operation

In [ ]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[1., 2., 9.],
        [7., 6., 5.]])

In [ ]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([18, 13])

In [ ]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([4., 4., 7.])

In [ ]:
# median
torch.median(e)

tensor(5.)

In [ ]:
# max and min
torch.max(e)
torch.min(e)

tensor(1.)

In [ ]:
# product
torch.prod(e)

tensor(3780.)

In [ ]:
# standard deviation
torch.std(e)

tensor(3.0332)

In [ ]:
# variance
torch.var(e)

tensor(9.2000)

In [ ]:
# argmax
torch.argmax(e)

tensor(2)

In [ ]:
# argmin
torch.argmin(e)

tensor(0)

### 4. Matrix operations

In [ ]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[3, 7, 8],
        [7, 9, 9]])
tensor([[1, 1],
        [4, 2],
        [4, 7]])


In [ ]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[63, 73],
        [79, 88]])

In [ ]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [ ]:
# transpose
torch.transpose(f, 0, 1)

tensor([[3, 7],
        [7, 9],
        [8, 9]])

In [ ]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[8., 2., 2.],
        [4., 8., 8.],
        [5., 0., 4.]])

In [ ]:
# determinant
torch.det(h)

tensor(224.)

In [ ]:
# inverse
torch.inverse(h)

tensor([[ 0.1429, -0.0357,  0.0000],
        [ 0.1071,  0.0982, -0.2500],
        [-0.1786,  0.0446,  0.2500]])

### 5. Comparison operations

In [ ]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[5, 0, 1],
        [1, 1, 3]])
tensor([[2, 6, 3],
        [5, 2, 5]])


In [ ]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

tensor([[True, True, True],
        [True, True, True]])

### 6. Special functions

In [ ]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[0., 6., 4.],
        [4., 8., 6.]])

In [ ]:
# log
torch.log(k)

tensor([[1.6094, 1.3863, 0.0000],
        [1.9459, 0.0000, 2.0794]])

In [ ]:
# exp
torch.exp(k)

tensor([[1.4841e+02, 5.4598e+01, 2.7183e+00],
        [1.0966e+03, 2.7183e+00, 2.9810e+03]])

In [ ]:
# sqrt
torch.sqrt(k)

tensor([[2.2361, 2.0000, 1.0000],
        [2.6458, 1.0000, 2.8284]])

In [ ]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9933, 0.9820, 0.7311],
        [0.9991, 0.7311, 0.9997]])

In [ ]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.0180, 0.1192, 0.1192],
        [0.9820, 0.8808, 0.8808]])

In [ ]:
# relu
torch.relu(k)

tensor([[0., 6., 4.],
        [4., 8., 6.]])

## Inplace Operations

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.2018, 0.1089, 0.7653],
        [0.6473, 0.3401, 0.6406]])
tensor([[0.4749, 0.1632, 0.6222],
        [0.5379, 0.2758, 0.7180]])


In [ ]:
m.add_(n)

tensor([[0.6767, 0.2721, 1.3875],
        [1.1851, 0.6159, 1.3585]])

In [ ]:
m

tensor([[0.6767, 0.2721, 1.3875],
        [1.1851, 0.6159, 1.3585]])

In [ ]:
n

tensor([[0.4749, 0.1632, 0.6222],
        [0.5379, 0.2758, 0.7180]])

In [ ]:
torch.relu(m)

tensor([[0.6767, 0.2721, 1.3875],
        [1.1851, 0.6159, 1.3585]])

In [ ]:
m.relu_()

tensor([[0.6767, 0.2721, 1.3875],
        [1.1851, 0.6159, 1.3585]])

In [ ]:
m

tensor([[0.6767, 0.2721, 1.3875],
        [1.1851, 0.6159, 1.3585]])

## Copying a Tensor

In [ ]:
a = torch.rand(2,3)
a

tensor([[0.5153, 0.9985, 0.6783],
        [0.2776, 0.6227, 0.2982]])

In [ ]:
b = a

In [ ]:
b

tensor([[0.5153, 0.9985, 0.6783],
        [0.2776, 0.6227, 0.2982]])

In [ ]:
a[0][0] = 0

In [ ]:
a

tensor([[0.0000, 0.9985, 0.6783],
        [0.2776, 0.6227, 0.2982]])

In [ ]:
b

tensor([[0.0000, 0.9985, 0.6783],
        [0.2776, 0.6227, 0.2982]])

In [ ]:
id(a)

134838567488544

In [ ]:
id(b)

134838567488544

In [ ]:
b = a.clone()

In [ ]:
a

tensor([[0.0000, 0.9985, 0.6783],
        [0.2776, 0.6227, 0.2982]])

In [ ]:
b

tensor([[0.0000, 0.9985, 0.6783],
        [0.2776, 0.6227, 0.2982]])

In [ ]:
a[0][0] = 10

In [ ]:
a

tensor([[10.0000,  0.9985,  0.6783],
        [ 0.2776,  0.6227,  0.2982]])

In [ ]:
b

tensor([[0.0000, 0.9985, 0.6783],
        [0.2776, 0.6227, 0.2982]])

In [ ]:
id(a)

134838567488544

In [ ]:
id(b)

134838569581552